<?php
/**
 * Enhanced Notification Helpers
 * Functions to create notifications for various library events
 */

/**
 * Notify librarians about new borrow request
 */
function notifyLibrarianBorrowRequest($db, $requesterEmail, $bookTitle, $requestId) {
    // Get all librarian emails
    $stmt = $db->prepare("SELECT email FROM Users WHERE role = 'librarian'");
    $stmt->execute();
    $librarians = $stmt->fetchAll(PDO::FETCH_COLUMN);
    
    $message = "New borrow request from $requesterEmail for '$bookTitle' (Request #$requestId)";
    
    foreach ($librarians as $librarianEmail) {
        $insertStmt = $db->prepare("
            INSERT INTO Notifications (user_email, message, type)
            VALUES (?, ?, 'BorrowRequestPending')
        ");
        $insertStmt->execute([$librarianEmail, $message]);
    }
    
    return true;
}

/**
 * Notify librarians about new return request
 */
function notifyLibrarianReturnRequest($db, $requesterEmail, $bookTitle, $transactionId) {
    $stmt = $db->prepare("SELECT email FROM Users WHERE role = 'librarian'");
    $stmt->execute();
    $librarians = $stmt->fetchAll(PDO::FETCH_COLUMN);
    
    $librarianMessage = "New return request from $requesterEmail for '$bookTitle' (Transaction #$transactionId)";
    $userMessage = "Return request for '$bookTitle' (Transaction #$transactionId) is pending librarian approval";
    
    // Notify librarians
    foreach ($librarians as $librarianEmail) {
        $insertStmt = $db->prepare("
            INSERT INTO Notifications (user_email, message, type)
            VALUES (?, ?, 'ReturnRequestPending')
        ");
        $insertStmt->execute([$librarianEmail, $librarianMessage]);
    }
    
    // Notify user
    $userInsertStmt = $db->prepare("
        INSERT INTO Notifications (user_email, message, type)
        VALUES (?, ?, 'ReturnRequestPending')
    ");
    $userInsertStmt->execute([$requesterEmail, $userMessage]);
    
    return true;
}

/**
 * Notify librarians about new book added
 */
function notifyLibrarianBookAdded($db, $bookTitle, $addedBy) {
    $stmt = $db->prepare("SELECT email FROM Users WHERE role = 'librarian'");
    $stmt->execute();
    $librarians = $stmt->fetchAll(PDO::FETCH_COLUMN);
    
    $message = "New book '$bookTitle' has been added to the collection by $addedBy";
    
    foreach ($librarians as $librarianEmail) {
        $insertStmt = $db->prepare("
            INSERT INTO Notifications (user_email, message, type)
            VALUES (?, ?, 'BookAdded')
        ");
        $insertStmt->execute([$librarianEmail, $message]);
    }
    
    return true;
}

/**
 * Notify librarians about inventory update
 */
function notifyLibrarianInventoryUpdate($db, $shelfNumber, $action, $count) {
    $stmt = $db->prepare("SELECT email FROM Users WHERE role = 'librarian'");
    $stmt->execute();
    $librarians = $stmt->fetchAll(PDO::FETCH_COLUMN);
    
    $message = "Inventory update: $action $count books on Shelf #$shelfNumber";
    
    foreach ($librarians as $librarianEmail) {
        $insertStmt = $db->prepare("
            INSERT INTO Notifications (user_email, message, type)
            VALUES (?, ?, 'InventoryUpdate')
        ");
        $insertStmt->execute([$librarianEmail, $message]);
    }
    
    return true;
}

/**
 * Notify librarians about user transaction activity
 */
function notifyLibrarianUserTransaction($db, $userEmail, $transactionType, $bookTitle) {
    $stmt = $db->prepare("SELECT email FROM Users WHERE role = 'librarian'");
    $stmt->execute();
    $librarians = $stmt->fetchAll(PDO::FETCH_COLUMN);
    
    $message = "User $userEmail completed $transactionType for '$bookTitle'";
    
    foreach ($librarians as $librarianEmail) {
        $insertStmt = $db->prepare("
            INSERT INTO Notifications (user_email, message, type)
            VALUES (?, ?, 'UserTransaction')
        ");
        $insertStmt->execute([$librarianEmail, $message]);
    }
    
    return true;
}

/**
 * Notify librarians about report generation
 */
function notifyLibrarianReportGenerated($db, $reportType, $generatedBy) {
    $stmt = $db->prepare("SELECT email FROM Users WHERE role = 'librarian'");
    $stmt->execute();
    $librarians = $stmt->fetchAll(PDO::FETCH_COLUMN);
    
    $message = "Report '$reportType' has been generated by $generatedBy";
    
    foreach ($librarians as $librarianEmail) {
        $insertStmt = $db->prepare("
            INSERT INTO Notifications (user_email, message, type)
            VALUES (?, ?, 'ReportGenerated')
        ");
        $insertStmt->execute([$librarianEmail, $message]);
    }
    
    return true;
}

/**
 * Notify user about fine limit reached
 */
function notifyFineLimitReached($db, $userEmail, $totalFines) {
    $message = "Your total unpaid fines ($totalFines TK) have exceeded the limit. Please pay your fines to continue borrowing books.";
    
    $stmt = $db->prepare("
        INSERT INTO Notifications (user_email, message, type)
        VALUES (?, ?, 'FineLimitReached')
    ");
    $stmt->execute([$userEmail, $message]);
    
    return true;
}

/**
 * Notify user about payment confirmation
 */
function notifyPaymentConfirmation($db, $userEmail, $amount, $paymentMethod) {
    $message = "Payment of $amount TK received successfully via $paymentMethod. Your fines have been cleared.";
    
    $stmt = $db->prepare("
        INSERT INTO Notifications (user_email, message, type)
        VALUES (?, ?, 'PaymentConfirmation')
    ");
    $stmt->execute([$userEmail, $message]);
    
    return true;
}
?>
